// <auto-generated />
using System;
using Items.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Items.Migrations
{
    [DbContext(typeof(ItemsContext))]
    partial class ItemsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Items.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Technique"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Furniture"
                        },
                        new
                        {
                            ID = 3,
                            Name = "TV sets",
                            ParentId = 1
                        },
                        new
                        {
                            ID = 4,
                            Name = "Samsung",
                            ParentId = 3
                        },
                        new
                        {
                            ID = 5,
                            Name = "LG",
                            ParentId = 3
                        },
                        new
                        {
                            ID = 6,
                            Name = "Armchairs",
                            ParentId = 2
                        },
                        new
                        {
                            ID = 7,
                            Name = "Sofas",
                            ParentId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
